# Generated by Django 3.0.7 on 2023-04-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbaApp.Team')),
            ],
        ),
    ]
