# Generated by Django 3.0.7 on 2023-04-29 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=200)),
                ('abbreviation', models.CharField(default=0, max_length=3)),
                ('city', models.CharField(default=0, max_length=50)),
                ('state', models.CharField(default=0, max_length=50)),
                ('conference', models.CharField(default=0, max_length=50)),
                ('division', models.CharField(default=0, max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('team_ppg', models.CharField(default=0, max_length=50)),
                ('team_rpg', models.CharField(default=0, max_length=50)),
                ('team_apg', models.CharField(default=0, max_length=50)),
                ('opp_ppg', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='null', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('rebounds', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbaApp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('team1_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team2_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_comparisons', to='nbaApp.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_comparisons', to='nbaApp.Team')),
            ],
        ),
    ]
