# Generated by Django 3.0.7 on 2023-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
