# Generated by Django 3.0.7 on 2023-04-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lname',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
