# Generated by Django 3.0.7 on 2023-04-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaApp', '0002_auto_20230421_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='opp_ppg',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_apg',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_ppg',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_rpg',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
