# Generated by Django 3.0.7 on 2023-04-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nbaApp', '0003_auto_20230421_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('team1_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team2_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_comparisons', to='nbaApp.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_comparisons', to='nbaApp.Team')),
            ],
        ),
    ]
