# Generated by Django 3.0.7 on 2023-04-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbaApp', '0004_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='winner',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
